(cl:in-package custom_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          BOX-VAL
          BOX
          VELOCITY-VAL
          VELOCITY
          ANGLE-VAL
          ANGLE
          POSE-VAL
          POSE
          OBJ_LANE_NUMBER-VAL
          OBJ_LANE_NUMBER
          LABEL-VAL
          LABEL
          SCORE-VAL
          SCORE
          X-VAL
          X
          Y-VAL
          Y
          WIDTH-VAL
          WIDTH
          HEIGHT-VAL
          HEIGHT
          FRENET_LENGTH-VAL
          FRENET_LENGTH
          FRENET_DISTANCE-VAL
          FRENET_DISTANCE
          DIS_TO_LEFTBOUNDING-VAL
          DIS_TO_LEFTBOUNDING
          DIS_TO_RIGHTBOUNDING-VAL
          DIS_TO_RIGHTBOUNDING
          ID-VAL
          ID
))