// Generated by gencpp from file custom_msgs/TrajPredSingle.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_TRAJPREDSINGLE_H
#define CUSTOM_MSGS_MESSAGE_TRAJPREDSINGLE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <custom_msgs/DetectedObject.h>

namespace custom_msgs
{
template <class ContainerAllocator>
struct TrajPredSingle_
{
  typedef TrajPredSingle_<ContainerAllocator> Type;

  TrajPredSingle_()
    : header()
    , array_len(0)
    , objects()
    , id(0)  {
    }
  TrajPredSingle_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , array_len(0)
    , objects(_alloc)
    , id(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _array_len_type;
  _array_len_type array_len;

   typedef std::vector< ::custom_msgs::DetectedObject_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::custom_msgs::DetectedObject_<ContainerAllocator> >> _objects_type;
  _objects_type objects;

   typedef uint32_t _id_type;
  _id_type id;





  typedef boost::shared_ptr< ::custom_msgs::TrajPredSingle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::TrajPredSingle_<ContainerAllocator> const> ConstPtr;

}; // struct TrajPredSingle_

typedef ::custom_msgs::TrajPredSingle_<std::allocator<void> > TrajPredSingle;

typedef boost::shared_ptr< ::custom_msgs::TrajPredSingle > TrajPredSinglePtr;
typedef boost::shared_ptr< ::custom_msgs::TrajPredSingle const> TrajPredSingleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::TrajPredSingle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::TrajPredSingle_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msgs::TrajPredSingle_<ContainerAllocator1> & lhs, const ::custom_msgs::TrajPredSingle_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.array_len == rhs.array_len &&
    lhs.objects == rhs.objects &&
    lhs.id == rhs.id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msgs::TrajPredSingle_<ContainerAllocator1> & lhs, const ::custom_msgs::TrajPredSingle_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::TrajPredSingle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::TrajPredSingle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::TrajPredSingle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::TrajPredSingle_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::TrajPredSingle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::TrajPredSingle_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::TrajPredSingle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "10e9f71602422d72b4d2dcbad941f70d";
  }

  static const char* value(const ::custom_msgs::TrajPredSingle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x10e9f71602422d72ULL;
  static const uint64_t static_value2 = 0xb4d2dcbad941f70dULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::TrajPredSingle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/TrajPredSingle";
  }

  static const char* value(const ::custom_msgs::TrajPredSingle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::TrajPredSingle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 当前时刻下单目标轨迹序列\n"
"std_msgs/Header header\n"
"uint32 array_len # 序列长度，即目标的历史/未来轨迹序列长度\n"
"DetectedObject[] objects    # 轨迹序列\n"
"uint32 id # 目标ID\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: custom_msgs/DetectedObject\n"
"# 单个目标定义\n"
"std_msgs/Header header\n"
"\n"
"jsk_recognition_msgs/BoundingBox box\n"
"float32 velocity\n"
"float64 angle       # Angle [0 to 2*PI), allow rotated rects\n"
"geometry_msgs/Pose pose # 单目标位置信息\n"
"int32 obj_lane_number\n"
"\n"
"string label\n"
"float32 score\n"
"int32 x\n"
"int32 y\n"
"int32 width\n"
"int32 height\n"
"float32 frenet_length\n"
"float32 frenet_distance\n"
"float32 dis_to_leftBounding\n"
"float32 dis_to_rightBounding\n"
"\n"
"uint32 id   # 单目标id\n"
"================================================================================\n"
"MSG: jsk_recognition_msgs/BoundingBox\n"
"# BoundingBox represents a oriented bounding box.\n"
"Header header\n"
"geometry_msgs/Pose pose\n"
"geometry_msgs/Vector3 dimensions  # size of bounding box (x, y, z)\n"
"# You can use this field to hold value such as likelihood\n"
"float32 value\n"
"uint32 label\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::custom_msgs::TrajPredSingle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::TrajPredSingle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.array_len);
      stream.next(m.objects);
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrajPredSingle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::TrajPredSingle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::TrajPredSingle_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "array_len: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.array_len);
    s << indent << "objects[]" << std::endl;
    for (size_t i = 0; i < v.objects.size(); ++i)
    {
      s << indent << "  objects[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::custom_msgs::DetectedObject_<ContainerAllocator> >::stream(s, indent + "    ", v.objects[i]);
    }
    s << indent << "id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_TRAJPREDSINGLE_H
